name: easy_contacts
description: "Simplify your contact management with ease."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.6.7
  fluttertoast: ^8.2.4
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true